-- Enable vector extension (if not already enabled)
create extension if not exists vector;

-- Create tables in Supabase
create table repositories (
    id uuid default gen_random_uuid() primary key,
    name text not null,
    owner text not null,
    repo_url text unique not null,
    private boolean default false,
    pat_token text,
    status text default 'pending',
    error_message text,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

create table documents (
    id bigint generated by default as identity primary key,
    repository_id uuid references repositories(id),
    file_name text not null,
    content text not null,
    embedding vector(1536),
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create vector similarity search index
create index on documents using ivfflat (embedding vector_cosine_ops) with (lists = 100); 